CarProject/Areas/Admin/Controllers/FileManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using CarProject.App_extension;

namespace CarProject.Areas.Admin.Controllers
{
    public class FileManagerController : Controller
    {
        //
        // GET: /Admin/FileManager/

        public ActionResult Index(string path)
        {
            return View(model: path);
        }


        public JsonResult GetImages(string path)
        {
            var rtdirel = "~/Publics/Filemanager";
            if (path != null && !path.IsNullOrWhiteSpace())
                rtdirel = Path.Combine(rtdirel, path).Replace('\\', '/');
            
            var dic = new DirectoryInfo(Server.MapPath(rtdirel));
            List<dynamic> dirs = new List<dynamic>();
            List<dynamic> images = new List<dynamic>();
            foreach (var item in dic.GetDirectories())
            {
                dirs.Add(new { name = item.Name, path = Url.Content(Path.Combine(rtdirel, item.Name).Replace('\\', '/')) });
            }
            foreach (var item in dic.GetFiles())
            {
                images.Add(new { name = item.Name, path = Url.Content(Path.Combine(rtdirel, item.Name).Replace('\\', '/')), path2 = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content(Path.Combine(rtdirel, item.Name).Replace('\\', '/'))) });
            }
            return Json(new { DIR = dirs, IMGS = images }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public void RenameRequest(string address, string newname)
        {
            var file = new FileInfo(Server.MapPath(address));
            if (file.Attributes == FileAttributes.Directory && Directory.Exists(file.FullName))
                Directory.Move(file.FullName, file.FullName.Replace(file.Name, newname));
            else if (file.Exists)
                file.MoveTo(file.FullName.Replace(file.Name, newname));
            
        }
        [HttpPost]
        public void CreateNewDir(string current, string dir)
        {
            if (dir.IsNullOrWhiteSpace())
                return;
            var rtdirel = "~/Publics/Filemanager";
            if (current != null && !current.IsNullOrWhiteSpace())
                rtdirel = Path.Combine(rtdirel, current).Replace('\\', '/');

            rtdirel = Path.Combine(rtdirel, dir).Replace('\\', '/');

            DirectoryInfo dirinf = new DirectoryInfo(Server.MapPath(rtdirel));
            if (!dirinf.Exists)
                dirinf.Create(Directory.GetAccessControl(Server.MapPath("~/Publics/Filemanager")));
        }

        [HttpPost]
        public void UploadFile(string current)
        {
            if (Request.Files.AllKeys.Contains("file"))
            {
                var rtdirel = "~/Publics/Filemanager";
                if (current != null && !current.IsNullOrWhiteSpace())
                    rtdirel = Path.Combine(rtdirel, current).Replace('\\', '/');
                var dir = new DirectoryInfo(Server.MapPath(rtdirel));
                var name = Request.Files[0].FileName.Replace("C:\\fakepath\\", "");
                Request.Files["file"].SaveAs(Path.Combine(dir.FullName, name));
            }
        }


        public ActionResult tinymcefm(string id)
        {
            return View(model: id);
        }
        public ActionResult tinymcefm_selector(string id)
        {
            return View(model: id);
        }

        public ActionResult tinymcefm2(string id)
        {
            return View(model: id);
        }
        public ActionResult tinymcefm2_selector(string id)
        {
            return View(model: id);
        }
    }
}

CarProject/Areas/Admin/Views/FileManager/tinymcefm.cshtml
@{
    //ViewBag.Title = "مدیریت فایل";
    Layout = null;
}


<div id="filebrowserBack" tabindex="0">
    <div id="filebrowser" tabindex="1">
        <div id="statusbar" tabindex="1.0">
            <a href="javascript:void()" onclick="document.getElementById('filebrowserBack').style.display = 'none';" style="color:red;" title="close"> &times;</a>
            |
            <span>انتخاب فایل تصویر</span>
        </div>
        <div id="topToolbar" tabindex="1.1">
            <a href="javascript: void()" class="gia-upload" onclick="document.getElementById('FileUploader').style.display = 'flex';">آپلود فایل</a> |
            <a href="javascript: void()" class="gia-home" onclick="GetFiles('')">پوشه اصلی</a> | 
            <a href="javascript: void()" class="gia-back" onclick="GetFiles(dirHistory.pop())">برگشت به پوشه قبلی</a> | 
            <a href="javascript: void()" class="gia-refresh" onclick="dirHistory = [] ;GetFiles(currentDir);">بروزرسانی</a> |
            <a href="javascript: void()" class="gia-newdir" onclick="document.getElementById('NewFolderCreate').style.display = 'flex'">پوشه جدید</a> 
        </div>

        <div id="navigation" tabindex="1.2"></div>

        <div id="FilesContainer" tabindex="1.3">

        </div>
    </div>

    <form method="post" id="renameContainer" class="box1" tabindex="2">
        <h3>تغییر نام فایل</h3>
        <input type="hidden" name="filepath" />
        <input type="text" name="filename" id="fileBrowserTxtName" />
        <div id="renameaction" class="actionbar">
            <input type="button" value="انصراف" onclick="document.getElementById('renameContainer').style.display = 'none';" class="button yellow" />
            <input type="button" value="تغییر نام" class="button green" onclick="RenameChangeRequest(event)" />
        </div>
    </form>
    <form id="NewFolderCreate" class="box1">
        <h3>ایجاد پوشه جدید</h3>
        <input type="text" name="NewDirectorytxt" placeholder="folder name" />
        <div  class="actionbar">
            <input type="button" value="انصراف" onclick="document.getElementById('NewFolderCreate').style.display = 'none';" class="button yellow" />
            <input type="button" value="تایید" class="button green" onclick="createNewDirRequest(this)" />
        </div>
    </form>
    <form id="FileUploader" class="box1" enctype="multipart/form-data">
        <h3>آپلود کردن فایل</h3>
        <input type="file" name="file" />
        <div class="actionbar" >
            <input type="button" value="انصراف" onclick="document.getElementById('FileUploader').style.display = 'none';" class="button yellow" />
            <input type="button" value="تایید" class="button green" onclick="UploadRequest(this)" />
        </div>
    </form>
    <div id="ContextMenu" tabindex="3">
        <a href="javascript:void()" onclick="RenameObject()" class="gia-rename">تغییر نام فایل</a>
        <a href="javascript:void()" onclick="" class="gia-remove">حذف فایل</a>
    </div>
</div>


    <style>
        
        #filebrowserBack {
            display:none ;
            position:fixed;
            top:0; bottom:0; left:0; right:0; 
            background:rgba(0,0,0,0.7);
            z-index:75535;
        }
        #statusbar {
            background:#eaeaea;
            border-bottom:thin solid #888;
            padding:0 5px;
        }
        #topToolbar {
            border-bottom:thin solid #888;
        }
        #filebrowser {
            position:absolute;
            top:0; bottom:0; left:0; right:0; 
            background:white;
            margin:auto;
            width:95%;
            height:95%;
            overflow:auto;
        }

        #FilesContainer {
            display:flex; /*justify-content:center; align-items:stretch;*/
            flex-wrap:wrap;
        }
            #FilesContainer > * {
                position:relative;
                width:200px; height:120px;
                display:flex; flex-direction:column; justify-content:center; align-items:center;
                border:thin solid #888;
                margin:5px;
                border-radius:5px;
                overflow:hidden;
                text-align:center;
                transition:ease-in-out 0.3s;
                background:white;
            }
                #FilesContainer > *:hover {
                    box-shadow:0 0 3px 0 #000;
                    /*transform: scale(1.05);*/
                }
            #FilesContainer  img {
                
            }
            #FilesContainer imgname {
                position:absolute; left:0; right:0; bottom:0;
                background:rgba(0, 0, 0, 0.60);
                color:white;
                z-index: 1;
            }

        #ContextMenu {
            position:fixed;
            display:none; flex-direction:column;
            background:white;
            border:thin solid #888;
            box-shadow:0 0 2px 0 #000;
        }
            #ContextMenu a {
                padding:5px;
            }
                #ContextMenu a:hover {
                    color: white;
                    background: #888;
                }

        .box1 {
            position:fixed;
            left:0; right:0; top:0; bottom:0;
            margin:auto;
            width:300px;
            height:130px;
            border:thin solid #888;
            box-shadow: 0 0 5px 0 #000;
            background:white;
            display:none;
            flex-direction:column;
            justify-content:flex-start; align-items:stretch;
            padding:5px;
        }
            .box1 h3 {
                margin:-5px;
                margin-bottom:5px;
                padding:0 5px;
                background:#888;
                color:white;
                font-size:90%;
            }

            .box1 input:not([type=button]) {
                border: thin solid #777;
                font-family:yekan;
                direction:ltr;
                font-size:100%;
                padding:1px 3px;
                min-height:40px;
            }
            .box1 .actionbar {
                display:flex; justify-content:center;
            }
    </style>

    <script>
        var fieldname = "";
        var wind = "";

        tinymce.init({
            selector: '#@Model',
            menubar: false,
            plugins: "directionality,link,hr,table,emoticons,preview,image,media,code",
            toolbar: "fontsizeselect styleselect removeformat | ltr rtl | alignleft aligncenter alignright alignjustify | bold italic underline strikethrough | undo redo | cut copy paste | bullist numlist | hr link unlink | image media | table tabledelete tabledelete tablemergecells tablesplitcells tableinsertrowbefore tableinsertrowbefore tableinsertrowbefore tablerowprops tablecutrow tablecopyrow tablepasterowbefore tablepasterowafter tableinsertcolbefore tableinsertcolafter tabledeletecol | emoticons preview | code",
            content_css: "@Url.Content("~/Publics/Styles/fonts/Fonts.css"),@Url.Content("~/Areas/Admin/Files/StyleAndScripts/Default/tinymce01.css")",
            directionality: 'rtl',
            min_height: 300,

            relative_urls: false,
            convert_urls: false,
            remove_script_host: false,

            automatic_uploads: true,
            file_browser_callback: function (field_name, url, type, win) {
                //win.document.getElementById(field_name).value = 'my browser value';

                fieldname = field_name;
                wind = win;
                document.getElementById("filebrowserBack").style.display = "inherit";
                GetFiles('');
            },


            video_template_callback: function (data) {

                url = "https://www.aparat.com/video/video/embed/videohash/" + data.source1 + "/vt/frame";

                return '<div class="h_iframe-aparat_embed_frame"> <span style="display: block;padding-top: 57%"></span><iframe src="' + url + '" allowFullScreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></div>';

            }
         });

        var dirHistory = [];
        var currentDir = "";

        function GetFiles(path) {

            dirHistory.push(currentDir);
            currentDir = path;
            fc = document.getElementById("FilesContainer");
            fc.innerHTML = "";

            $.get("@Url.Action("GetImages","FileManager")", { path: path }, function (e) {
                for (var i = 0; i < e["DIR"].length; i++) {
                    a = document.createElement("a");
                    a.href = "javascript: void();";
                    a.classList.add("gia-directory");
                    a.classList.add("dir");
                    a.setAttribute("data-path", e["DIR"][i]["path"]);
                    a.setAttribute("data-name", e["DIR"][i]["name"]);

                    a.onclick = function () { GetFiles(this.getAttribute("data-name")); }
                    a.oncontextmenu = function (e) { OnContextMenuHandler(e); };

                    a.textContent = e["DIR"][i]["name"];
                    fc.appendChild(a);
                }

                for (var i = 0; i < e["IMGS"].length; i++) {
                    img = document.createElement("img");
                    img.src = e["IMGS"][i]["path"];
                    //img.setAttribute("data-title", e["IMGS"][i]["name"]);

                    secname = document.createElement("section");
                    secname.classList.add("imgname");
                    secname.innerHTML = e["IMGS"][i]["name"];

                    a = document.createElement("a");
                    a.classList.add("img");
                    a.setAttribute("data-path", e["IMGS"][i]["path"]);
                    a.setAttribute("data-name", e["IMGS"][i]["name"]);

                    a.onclick = function () { wind.document.getElementById(fieldname).value = this.getAttribute("data-path"); document.getElementById("filebrowserBack").style.display = "none"; };
                    a.oncontextmenu = function (e) { OnContextMenuHandler(e); };

                    a.href = "javascript:void();";

                    a.appendChild(img);
                    a.appendChild(secname);



                    fc.appendChild(a);
                }
            });


        }

        var ContextMenuSelectedElement = "";
        function OnContextMenuHandler(e) {
            e.preventDefault();
            //alert(e.offsetX);

            ContextMenuSelectedElement = $(e.target).closest('a');

            cnm = document.getElementById("ContextMenu");
            cnm.style.left = e.clientX + "px";
            cnm.style.top = e.clientY + "px";
            cnm.style.display = "flex";
            cnm.hideFocus = true;
            cnm.focus();
        }
        document.getElementById("filebrowser").addEventListener("mousedown", function (e) { document.getElementById("ContextMenu").style.display = "none"; });

        function RenameObject() {
            document.getElementById("ContextMenu").style.display = "none";

            rcn = document.getElementById("renameContainer");
            rcn.style.display = "flex";

            $("input[type=hidden]", rcn).val($(ContextMenuSelectedElement).attr("data-path"));
            $("input[type=text]", rcn).val($(ContextMenuSelectedElement).attr("data-name"));
        }

        function RenameChangeRequest(e) {
            document.getElementById("renameContainer").style.display = "none";
            $.post("@Url.Action("RenameRequest","FileManager")", { address: e.target.form.filepath.value, newname: e.target.form.filename.value }, function (res) {
                GetFiles(currentDir);
            })
        }

        function createNewDirRequest(obj) {
            if (obj.form.NewDirectorytxt.value == "")
                return;
            fname = obj.form.NewDirectorytxt.value;
            obj.form.NewDirectorytxt.value = "";
            document.getElementById('NewFolderCreate').style.display = 'none';
            $.post("@Url.Action("CreateNewDir","FileManager")", { current: currentDir, dir: fname }, function () { GetFiles(currentDir); });
        }

        function UploadRequest(obj) {
            fd = new FormData();

            fd.append("file", obj.form.file.files[0], obj.form.file.value);
            fd.append("current", currentDir);


            $.ajax({ url: "@Url.Action("UploadFile","FileManager")", processData: false, cache: false, contentType: false, type: 'POST', data: fd, success: function (res) { document.getElementById('FileUploader').style.display = 'none'; GetFiles(currentDir); } });
        }

    </script>

CarProject/Areas/Admin/Views/FileManager/tinymcefm2.cshtml
@{
    //ViewBag.Title = "مدیریت فایل";
    Layout = null;
}


<div id="filebrowserBack" tabindex="0">
    <div id="filebrowser" tabindex="1">
        <div id="statusbar" tabindex="1.0">
            <a href="javascript:void()" onclick="document.getElementById('filebrowserBack').style.display = 'none';" style="color:red;" title="close"> &times;</a>
            |
            <span>انتخاب فایل تصویر</span>
        </div>
        <div id="topToolbar" tabindex="1.1">
            <a href="javascript: void()" class="gia-upload" onclick="document.getElementById('FileUploader').style.display = 'flex';">آپلود فایل</a> |
            <a href="javascript: void()" class="gia-home" onclick="GetFiles('')">پوشه اصلی</a> | 
            <a href="javascript: void()" class="gia-back" onclick="GetFiles(dirHistory.pop())">برگشت به پوشه قبلی</a> | 
            <a href="javascript: void()" class="gia-refresh" onclick="dirHistory = [] ;GetFiles(currentDir);">بروزرسانی</a> |
            <a href="javascript: void()" class="gia-newdir" onclick="document.getElementById('NewFolderCreate').style.display = 'flex'">پوشه جدید</a> 
        </div>

        <div id="navigation" tabindex="1.2"></div>

        <div id="FilesContainer" tabindex="1.3">

        </div>
    </div>

    <form method="post" id="renameContainer" class="box1" tabindex="2">
        <h3>تغییر نام فایل</h3>
        <input type="hidden" name="filepath" />
        <input type="text" name="filename" id="fileBrowserTxtName" />
        <div id="renameaction" class="actionbar">
            <input type="button" value="انصراف" onclick="document.getElementById('renameContainer').style.display = 'none';" class="button yellow" />
            <input type="button" value="تغییر نام" class="button green" onclick="RenameChangeRequest(event)" />
        </div>
    </form>
    <form id="NewFolderCreate" class="box1">
        <h3>ایجاد پوشه جدید</h3>
        <input type="text" name="NewDirectorytxt" placeholder="folder name" />
        <div  class="actionbar">
            <input type="button" value="انصراف" onclick="document.getElementById('NewFolderCreate').style.display = 'none';" class="button yellow" />
            <input type="button" value="تایید" class="button green" onclick="createNewDirRequest(this)" />
        </div>
    </form>
    <form id="FileUploader" class="box1" enctype="multipart/form-data">
        <h3>آپلود کردن فایل</h3>
        <input type="file" name="file" />
        <div class="actionbar" >
            <input type="button" value="انصراف" onclick="document.getElementById('FileUploader').style.display = 'none';" class="button yellow" />
            <input type="button" value="تایید" class="button green" onclick="UploadRequest(this)" />
        </div>
    </form>
    <div id="ContextMenu" tabindex="3">
        <a href="javascript:void()" onclick="RenameObject()" class="gia-rename">تغییر نام فایل</a>
        <a href="javascript:void()" onclick="" class="gia-remove">حذف فایل</a>
    </div>
</div>


    <style>
        
        #filebrowserBack {
            display:none ;
            position:fixed;
            top:0; bottom:0; left:0; right:0; 
            background:rgba(0,0,0,0.7);
            z-index:75535;
        }
        #statusbar {
            background:#eaeaea;
            border-bottom:thin solid #888;
            padding:0 5px;
        }
        #topToolbar {
            border-bottom:thin solid #888;
        }
        #filebrowser {
            position:absolute;
            top:0; bottom:0; left:0; right:0; 
            background:white;
            margin:auto;
            width:95%;
            height:95%;
            overflow:auto;
        }

        #FilesContainer {
            display:flex; /*justify-content:center; align-items:stretch;*/
            flex-wrap:wrap;
        }
            #FilesContainer > * {
                position:relative;
                width:200px; height:120px;
                display:flex; flex-direction:column; justify-content:center; align-items:center;
                border:thin solid #888;
                margin:5px;
                border-radius:5px;
                overflow:hidden;
                text-align:center;
                transition:ease-in-out 0.3s;
                background:white;
            }
                #FilesContainer > *:hover {
                    box-shadow:0 0 3px 0 #000;
                    /*transform: scale(1.05);*/
                }
            #FilesContainer  img {
                
            }
            #FilesContainer imgname {
                position:absolute; left:0; right:0; bottom:0;
                background:rgba(0, 0, 0, 0.60);
                color:white;
                z-index: 1;
            }

        #ContextMenu {
            position:fixed;
            display:none; flex-direction:column;
            background:white;
            border:thin solid #888;
            box-shadow:0 0 2px 0 #000;
        }
            #ContextMenu a {
                padding:5px;
            }
                #ContextMenu a:hover {
                    color: white;
                    background: #888;
                }

        .box1 {
            position:fixed;
            left:0; right:0; top:0; bottom:0;
            margin:auto;
            width:300px;
            height:130px;
            border:thin solid #888;
            box-shadow: 0 0 5px 0 #000;
            background:white;
            display:none;
            flex-direction:column;
            justify-content:flex-start; align-items:stretch;
            padding:5px;
        }
            .box1 h3 {
                margin:-5px;
                margin-bottom:5px;
                padding:0 5px;
                background:#888;
                color:white;
                font-size:90%;
            }

            .box1 input:not([type=button]) {
                border: thin solid #777;
                font-family:yekan;
                direction:ltr;
                font-size:100%;
                padding:1px 3px;
                min-height:40px;
            }
            .box1 .actionbar {
                display:flex; justify-content:center;
            }
    </style>

    <script>
        var fieldname = "";
        var wind = "";

        tinymce.init({
            selector: '#@Model',
            menubar: false,
            plugins: "directionality,link,hr,table,emoticons,preview,image,media,code",
            toolbar: "fontsizeselect styleselect removeformat | ltr rtl | alignleft aligncenter alignright alignjustify | bold italic underline strikethrough | undo redo | cut copy paste | bullist numlist | hr link unlink | image media | table tabledelete tabledelete tablemergecells tablesplitcells tableinsertrowbefore tableinsertrowbefore tableinsertrowbefore tablerowprops tablecutrow tablecopyrow tablepasterowbefore tablepasterowafter tableinsertcolbefore tableinsertcolafter tabledeletecol | emoticons preview | code",
            content_css: "@Url.Content("~/Publics/Styles/fonts/Fonts.css"),@Url.Content("~/Areas/Admin/Files/StyleAndScripts/Default/tinymce01.css")",
            directionality: 'rtl',
            min_height: 300,

            relative_urls: false,
            convert_urls: false,
            remove_script_host: false,

            automatic_uploads: true,
            file_browser_callback: function (field_name, url, type, win) {
                //win.document.getElementById(field_name).value = 'my browser value';

                fieldname = field_name;
                wind = win;
                document.getElementById("filebrowserBack").style.display = "inherit";
                GetFiles('');
            },


            video_template_callback: function (data) {

                url = "https://www.aparat.com/video/video/embed/videohash/" + data.source1 + "/vt/frame";

                return '<div class="h_iframe-aparat_embed_frame"> <span style="display: block;padding-top: 57%"></span><iframe src="' + url + '" allowFullScreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></div>';

            }
         });

        var dirHistory = [];
        var currentDir = "";

        function GetFiles(path) {

            dirHistory.push(currentDir);
            currentDir = path;
            fc = document.getElementById("FilesContainer");
            fc.innerHTML = "";

            $.get("@Url.Action("GetImages","FileManager")", { path: path }, function (e) {
                for (var i = 0; i < e["DIR"].length; i++) {
                    a = document.createElement("a");
                    a.href = "javascript: void();";
                    a.classList.add("gia-directory");
                    a.classList.add("dir");
                    a.setAttribute("data-path", e["DIR"][i]["path"]);
                    a.setAttribute("data-name", e["DIR"][i]["name"]);

                    a.onclick = function () { GetFiles(this.getAttribute("data-name")); }
                    a.oncontextmenu = function (e) { OnContextMenuHandler(e); };

                    a.textContent = e["DIR"][i]["name"];
                    fc.appendChild(a);
                }

                for (var i = 0; i < e["IMGS"].length; i++) {
                    img = document.createElement("img");
                    img.src = e["IMGS"][i]["path"];
                    //img.setAttribute("data-title", e["IMGS"][i]["name"]);

                    secname = document.createElement("section");
                    secname.classList.add("imgname");
                    secname.innerHTML = e["IMGS"][i]["name"];

                    a = document.createElement("a");
                    a.classList.add("img");
                    a.setAttribute("data-path", e["IMGS"][i]["path2"]);
                    a.setAttribute("data-name", e["IMGS"][i]["name"]);

                    a.onclick = function () { wind.document.getElementById(fieldname).value = this.getAttribute("data-path"); document.getElementById("filebrowserBack").style.display = "none"; };
                    a.oncontextmenu = function (e) { OnContextMenuHandler(e); };

                    a.href = "javascript:void();";

                    a.appendChild(img);
                    a.appendChild(secname);



                    fc.appendChild(a);
                }
            });


        }

        var ContextMenuSelectedElement = "";
        function OnContextMenuHandler(e) {
            e.preventDefault();
            //alert(e.offsetX);

            ContextMenuSelectedElement = $(e.target).closest('a');

            cnm = document.getElementById("ContextMenu");
            cnm.style.left = e.clientX + "px";
            cnm.style.top = e.clientY + "px";
            cnm.style.display = "flex";
            cnm.hideFocus = true;
            cnm.focus();
        }
        document.getElementById("filebrowser").addEventListener("mousedown", function (e) { document.getElementById("ContextMenu").style.display = "none"; });

        function RenameObject() {
            document.getElementById("ContextMenu").style.display = "none";

            rcn = document.getElementById("renameContainer");
            rcn.style.display = "flex";

            $("input[type=hidden]", rcn).val($(ContextMenuSelectedElement).attr("data-path"));
            $("input[type=text]", rcn).val($(ContextMenuSelectedElement).attr("data-name"));
        }

        function RenameChangeRequest(e) {
            document.getElementById("renameContainer").style.display = "none";
            $.post("@Url.Action("RenameRequest","FileManager")", { address: e.target.form.filepath.value, newname: e.target.form.filename.value }, function (res) {
                GetFiles(currentDir);
            })
        }

        function createNewDirRequest(obj) {
            if (obj.form.NewDirectorytxt.value == "")
                return;
            fname = obj.form.NewDirectorytxt.value;
            obj.form.NewDirectorytxt.value = "";
            document.getElementById('NewFolderCreate').style.display = 'none';
            $.post("@Url.Action("CreateNewDir","FileManager")", { current: currentDir, dir: fname }, function () { GetFiles(currentDir); });
        }

        function UploadRequest(obj) {
            fd = new FormData();

            fd.append("file", obj.form.file.files[0], obj.form.file.value);
            fd.append("current", currentDir);


            $.ajax({ url: "@Url.Action("UploadFile","FileManager")", processData: false, cache: false, contentType: false, type: 'POST', data: fd, success: function (res) { document.getElementById('FileUploader').style.display = 'none'; GetFiles(currentDir); } });
        }

    </script>